name: Code Test
on: [push, pull_request]

jobs:
    test:
        name: Test
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Go
              uses: actions/setup-go@v3.2.1
              with:
                  go-version-file: "./go.mod"
            - name: Cache tools
              uses: actions/cache@v3
              with:
                  path: |
                      ~/go/bin
                      ~/go/pkg/mod
                  key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            - name: Test
              run: make test
            - name: Coverage
              run: make coverage
